### ISSUE TITLE
优酷源解码失败

### ISSUE THREAD

**Issue by wcavell** [lxrite/DawnPlayer#1]
你好，我用你winrt的flv分离器播放不了优酷的视频，而且如果分辨率在720p或以上很容易播放2秒就表示播放结束了。不知道问题出在哪里。

**Comment by lxrite** [comment]
你好,

> 我用你winrt的flv分离器播放不了优酷的视频

我测试的几个优酷的视频都是可以播的，可以提供下你测试无法播放的优酷的`视频ID`和`视频分辨率(宽x高)`吗？

我刚才试了下优酷分辨率为`1105x622`的FLV会提示播放失败，原因似乎`WinRT`不允许设置`VideoEncodingProperties::Width`为奇数，如果设置为`1104`或`1106`就可以播放了，我之后会修复这个问题。

> 而且如果分辨率在720p或以上很容易播放2秒就表示播放结束了。

播放2秒就结束触发的是`MediaFailed`还是`MediaEnded`事件呢？如果可以也麻烦你提供下这个视频的ID。

感谢你的反馈！

**Comment by wcavell** [comment]
我的好像由于Debug模式播放2秒触发MediaEnded，这个问题在Release没有出现了。分辨率那问题确实是你所说的那样，修改为偶数后，没有解码失败的提示了。
还有一个问题，就是频繁随意Seek时有可能触发MediaFailed 
错误信息是：MF_MEDIA_ENGINE_ERR_DECODE : HRESULT - 0xC00D36B6

**Comment by lxrite** [comment]
> 1.Debug模式播放2秒触发MediaEnded
> 
> 2.频繁随意Seek时有可能触发MediaFailed

嗯，已确认确实是存在这两个问题，并且这两个问题似乎只有在WinRT上会出现，Windows Phone Silverlight上是正常的。
我会在定位问题所在后修复这些问题。

**Comment by lxrite** [comment]
关于

> Debug模式播放2秒触发MediaEnded

这个问题，是由于在Demo中没有维持对flv_media_stream_source对象的引用，其析构函数在播放期间过早的被调用（Release下也会发生只是概率比较低），我更新了下WinRT Demo的代码，你试下新的Demo是否解决了这个问题。
