### ISSUE TITLE
flv_player close方法

### ISSUE THREAD

**Issue by wcavell** [lxrite/DawnPlayer#2]
在新商店审核错误：“dawn_player.flv_player 包含大小写不一致的方法 Close 和 close。重载方法必须使用相同的大小写。”
在生成winmd的时候会多出一个大写Close方法，可能是跟flv_player的小写close方法有歧义吧，Windows 运行时元数据验证就会失败，改一下名称就可以了

**Comment by lxrite** [comment]
感谢反馈，我周末修改下。
